version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - llm-network

  chroma:
    image: chromadb/chroma
    container_name: chroma-dev
    restart: unless-stopped
    ports:
      - "8010:8000"
    volumes:
      - ../chroma/vector_db:/chroma/chroma

    networks:
      - llm-network

volumes:
  postgres_data:

networks:
  llm-network:
    driver: bridge
