version: "3.8"

services:
  backend:
    build:
      context: ../../backend
    container_name: backend
    # env_file:
    #   - ../../backend/.env
    environment:
      ML_BASE_URL: http://llm:9000
      #DB_HOST: mysql
    ports:
      - "8000:8000"
    volumes:
      - ../../backend:/backendWorkspace
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /backendWorkspace
    depends_on:
      - llm
      # - mysql

  llm:
    build:
      context: ../../llmServer
    container_name: llm
    env_file:
      - ../../llmServer/.env
    ports:
      - "9000:9000"
    volumes:
      - ../../llmServer:/llmWorkspace
    command: uvicorn app.main:app --host 0.0.0.0 --port 9000  --reload-dir /llmWorkspace

  # mysql:
  #   image: mysql:8.0
  #   container_name: mysql
  #   env_file:
  #     - ./backend/.env
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:
